table 'Dim Customers'
	lineageTag: 7fc0f464-cf07-452f-a451-83578b344b12

	column 'Customer ID'
		dataType: string
		lineageTag: 7f38a552-fb16-4263-a1b1-32bf276f4b99
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 29860b14-be5c-466c-b0c8-e7ebe369d276
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 62293de1-c201-418e-a3a8-e910cb359ceb
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: f7b3c956-0bcc-4712-9866-b76d8c207f4f
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Pincode
		dataType: int64
		formatString: 0
		lineageTag: daa4b718-18fa-4257-ae21-d2123fa0e370
		summarizeBy: none
		sourceColumn: Pincode

		annotation SummarizationSetBy = Automatic

	column EmailID
		dataType: string
		lineageTag: d45c3eb4-c655-462d-85d5-7d59301e7684
		summarizeBy: none
		sourceColumn: EmailID

		annotation SummarizationSetBy = Automatic

	column 'Phone Number'
		dataType: int64
		formatString: 0
		lineageTag: 659b0511-bac3-4a39-9138-166922ce3f28
		summarizeBy: none
		sourceColumn: Phone Number

		annotation SummarizationSetBy = Automatic

	partition 'Dim Customers' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\abhil\Downloads\Store+Data.xlsx"), null, true),
				    #"Dim Customers_Sheet" = Source{[Item="Dim Customers",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Dim Customers_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer ID", type text}, {"Customer Name", type text}, {"City", type text}, {"State", type text}, {"Pincode", Int64.Type}, {"EmailID", type text}, {"Phone Number", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

