table 'Fact Table'
	lineageTag: 83cc9aca-578c-45da-8a1c-54def26f5b21

	column 'Date (dd/mm/yyyy)'
		dataType: dateTime
		formatString: Short Date
		lineageTag: dd73a3f8-78c3-4ddf-ba1d-b903cb3e7aac
		summarizeBy: none
		sourceColumn: Date (dd/mm/yyyy)

		variation Variation
			isDefault
			relationship: 7ae1d2e4-a3ca-448a-bef8-bfade7e74e43
			defaultHierarchy: LocalDateTable_d27aeded-e645-4dbe-8c71-15d01827a12c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: ce2b4b88-794f-41f2-916c-aec939db65e5
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column PromotionID
		dataType: string
		lineageTag: f565b64a-5011-4df8-bffa-9b72ac54fe46
		summarizeBy: none
		sourceColumn: PromotionID

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 5289062d-abff-43f3-a71b-17d3a56d42f8
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: int64
		formatString: 0
		lineageTag: 62669847-136c-47c0-9162-a2077c4aceb6
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

	column 'Price Per Unit'
		dataType: int64
		formatString: 0
		lineageTag: b20e0e07-3bae-4887-8301-014af3c44a9f
		summarizeBy: sum
		sourceColumn: Price Per Unit

		annotation SummarizationSetBy = Automatic

	column 'Total Sales'
		dataType: double
		lineageTag: 98448573-9c61-4f0d-bc73-60ad2234b7af
		summarizeBy: sum
		sourceColumn: Total Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Discount Percentage'
		dataType: double
		lineageTag: 96680e45-84c5-43f0-8a81-8e2057aaf7fd
		summarizeBy: sum
		sourceColumn: Discount Percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Discount Value'
		dataType: double
		lineageTag: 2af3782e-60b9-40ce-9c4c-36a13997e690
		summarizeBy: sum
		sourceColumn: Discount Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Net Sales'
		dataType: double
		lineageTag: e2b7f0c6-d632-4a3f-9894-73ce0b3dc637
		summarizeBy: sum
		sourceColumn: Net Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit = 'Fact Table'[Net Sales]*0.1
		lineageTag: e3f42f2e-810c-4eb1-b83d-524c0fa561b5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order ID'
		dataType: int64
		formatString: 0
		lineageTag: a9031c94-889f-45b9-b0cc-55e52853c539
		summarizeBy: count
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	partition 'Fact Table' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\abhil\Downloads\Store+Data.xlsx"), null, true),
				    Sheet3_Sheet = Source{[Item="Sheet3",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet3_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date (dd/mm/yyyy)", type date}, {"CustomerID", Int64.Type}, {"PromotionID", type text}, {"Product ID", type text}, {"Units Sold", Int64.Type}, {"Price Per Unit", type any}, {"Total Sales", type any}, {"Discount Percentage", type any}, {"Discount Value", type any}, {"Net Sales", type any}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Product ID"}, #"Dim Product", {"ProductID"}, "Dim Product", JoinKind.LeftOuter),
				    #"Expanded Dim Product" = Table.ExpandTableColumn(#"Merged Queries", "Dim Product", {"Price Per Unit"}, {"Dim Product.Price Per Unit"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded Dim Product",{"Price Per Unit"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Units Sold", "Dim Product.Price Per Unit", "Total Sales", "Discount Percentage", "Discount Value", "Net Sales"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Dim Product.Price Per Unit", "Price Per Unit"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Total Sales.1", each [Units Sold]*[Price Per Unit]),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Added Custom",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Units Sold", "Price Per Unit", "Total Sales.1", "Total Sales", "Discount Percentage", "Discount Value", "Net Sales"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns1",{"Total Sales"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"Total Sales.1", "Total Sales"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Total Sales", type number}}),
				    #"Merged Queries1" = Table.NestedJoin(#"Changed Type1", {"PromotionID"}, #"Dim Promotion", {"PromotionID"}, "Dim Promotion", JoinKind.LeftOuter),
				    #"Expanded Dim Promotion" = Table.ExpandTableColumn(#"Merged Queries1", "Dim Promotion", {"Percentage"}, {"Dim Promotion.Percentage"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded Dim Promotion",null,0,Replacer.ReplaceValue,{"Dim Promotion.Percentage"}),
				    #"Reordered Columns2" = Table.ReorderColumns(#"Replaced Value",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Units Sold", "Price Per Unit", "Total Sales", "Dim Promotion.Percentage", "Discount Percentage", "Discount Value", "Net Sales"}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Reordered Columns2",{"Discount Percentage"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns2",{{"Dim Promotion.Percentage", "Discount Percentage"}}),
				    #"Added Custom1" = Table.AddColumn(#"Renamed Columns2", "Discount Value.1", each ([Total Sales]*[Discount Percentage])/100),
				    #"Removed Columns3" = Table.RemoveColumns(#"Added Custom1",{"Discount Value"}),
				    #"Reordered Columns3" = Table.ReorderColumns(#"Removed Columns3",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Units Sold", "Price Per Unit", "Total Sales", "Discount Percentage", "Discount Value.1", "Net Sales"}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Reordered Columns3",{{"Discount Value.1", "Discount Value"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns3",{{"Discount Percentage", type number}, {"Discount Value", type number}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type2", "Net Sales.1", each [Total Sales]-[Discount Value]),
				    #"Reordered Columns4" = Table.ReorderColumns(#"Added Custom2",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Units Sold", "Price Per Unit", "Total Sales", "Discount Percentage", "Discount Value", "Net Sales.1", "Net Sales"}),
				    #"Removed Columns4" = Table.RemoveColumns(#"Reordered Columns4",{"Net Sales"}),
				    #"Renamed Columns4" = Table.RenameColumns(#"Removed Columns4",{{"Net Sales.1", "Net Sales"}}),
				    #"Sorted Rows" = Table.Sort(#"Renamed Columns4",{{"Date (dd/mm/yyyy)", Order.Ascending}}),
				    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns5" = Table.RenameColumns(#"Added Index",{{"Index", "Order ID"}}),
				    #"Reordered Columns5" = Table.ReorderColumns(#"Renamed Columns5",{"Order ID", "Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Units Sold", "Price Per Unit", "Total Sales", "Discount Percentage", "Discount Value", "Net Sales"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Reordered Columns5",{{"Net Sales", type number}})
				in
				    #"Changed Type3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

